export const sampleReferrals = [
  {
    title: "Premium Web Hosting Service",
    description: "Get 20% commission on all web hosting referrals. High-quality hosting with 99.9% uptime guarantee, SSL certificates, and 24/7 support.",
    url: "https://example-hosting.com/ref/stotteyman",
    category: "Technology",
    commission_rate: 20.00,
    requirements: "Must be a new customer signup. Minimum 12-month contract required.",
    status: "active"
  },
  {
    title: "Digital Marketing Course",
    description: "Earn $50 for every student who enrolls in our comprehensive digital marketing course. Includes SEO, PPC, social media, and content marketing.",
    url: "https://digitalmarketingcourse.com/affiliate/stotteyman",
    category: "Education",
    commission_rate: 15.00,
    requirements: "Student must complete the full course to qualify for commission.",
    status: "active"
  },
  {
    title: "Fitness App Subscription",
    description: "Get $10 for every monthly subscription and $25 for annual subscriptions. Premium fitness tracking app with personalized workout plans.",
    url: "https://fitapp.com/ref/stotteyman",
    category: "Health & Wellness",
    commission_rate: 25.00,
    requirements: "User must maintain subscription for at least 30 days.",
    status: "active"
  },
  {
    title: "Cryptocurrency Trading Platform",
    description: "Earn 0.1% commission on all trading fees generated by your referrals. Advanced trading platform with low fees and high liquidity.",
    url: "https://cryptotrade.com/ref/stotteyman",
    category: "Finance",
    commission_rate: 0.10,
    requirements: "Referral must complete KYC verification and make at least one trade.",
    status: "active"
  },
  {
    title: "E-commerce Store Builder",
    description: "Get $100 commission for every premium plan subscription. All-in-one e-commerce solution with inventory management and payment processing.",
    url: "https://storebuilder.com/affiliate/stotteyman",
    category: "E-commerce",
    commission_rate: 30.00,
    requirements: "Customer must subscribe to premium plan for minimum 3 months.",
    status: "active"
  },
  {
    title: "Project Management Software",
    description: "Earn $75 for every team plan subscription. Professional project management tool with task tracking, time management, and team collaboration.",
    url: "https://projectmanager.com/ref/stotteyman",
    category: "SaaS",
    commission_rate: 20.00,
    requirements: "Team must have minimum 5 users and maintain subscription for 6 months.",
    status: "active"
  },
  {
    title: "Online Language Learning",
    description: "Get $30 commission for every premium language course enrollment. Learn 40+ languages with native speakers and AI-powered lessons.",
    url: "https://languagelearn.com/affiliate/stotteyman",
    category: "Education",
    commission_rate: 18.00,
    requirements: "Student must complete at least 10 lessons to qualify.",
    status: "active"
  },
  {
    title: "Cloud Storage Solution",
    description: "Earn $25 for every annual subscription. Secure cloud storage with automatic backup, file sharing, and collaboration tools.",
    url: "https://cloudstorage.com/ref/stotteyman",
    category: "Technology",
    commission_rate: 22.00,
    requirements: "Customer must subscribe to annual plan and use minimum 100GB storage.",
    status: "active"
  }
]