name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install sitemap generator
        run: npm install -g sitemap-generator-cli

      - name: Generate Sitemap
        run: |
          mkdir -p public
          sitemap-generator https://stotteyman.com \
            --output ./public/sitemap.xml \
            --strip-querystring \
            --max-entries 5000 \
            --include-url https://stotteyman.com \
            --crawl

      - name: Commit and Push sitemap.xml
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add public/sitemap.xml
          git diff --quiet || git commit -m "Automated sitemap update"
          git push
