name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g sitemap-generator-cli
      - run: sitemap-generator https://stotteyman.com -o ./public
      - name: Commit sitemap
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "update sitemap"
          git push
